%YAML:1.0
# MARK 这个东西本身长什么样(被检测物体的数学模型)  GeometryPolygon:点及点的排列顺序关系；凹转折锚点；图纸模型面积（模型单位下理论值）
# 只负责几何结构（不保存最终输出角）

schema_version: 1

polygons:

  - id: L0

    vertices:
      - [0, 0]
      - [30, 0]
      - [30, 8]
      - [8, 8]
      - [8, 30]
      - [0, 30]

    anchor: [8, 8]

    area: 416


  - id: L2

    vertices:
      - [80, 80]
      - [50, 80]
      - [50, 72]
      - [72, 72]
      - [72, 50]
      - [80, 50]

    anchor: [72, 72]

    area: 416


  - id: L3

    vertices:
      - [0, 80]
      - [30, 80]
      - [30, 72]
      - [8, 72]
      - [8, 50]
      - [0, 50]

    anchor: [8, 72]

    area: 416


  - id: M1

    vertices:
      - [66, 0]
      - [80, 0]
      - [80, 14]
      - [72, 14]
      - [72, 8]
      - [66, 8]

    anchor: [72, 8]

    area: 160


  - id: S1a

    vertices:
      - [50, 0]
      - [58, 0]
      - [58, 8]
      - [50, 8]

    anchor: [54, 4]

    area: 64


  - id: S1b

    vertices:
      - [72, 22]
      - [80, 22]
      - [80, 30]
      - [72, 30]

    anchor: [76, 26]

    area: 64